workflows:
  android-workflow:
    name: Build APK for Android
    max_build_duration: 15
    environment:
      flutter: stable
      android_signing:
        - keystore_reference
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - sagardiahurtadoraphael@gmail.com
